//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Scripts.Com.Jschiff.Tactics.Common.Model.Arena
{

  /**
   * A tile is one unit on the terrain.
   */
  public class Tile {
    
    public Tile () {
    }
  }
}

